name: Run CI checks
on: [pull_request]
jobs:
  test-store:
    runs-on: ubuntu-latest
    name: Test Store <-- the name that will appear on the Actions UI
    steps:
      - uses: actions/checkout@v1 <-- checkout whatever branch the PR is using
      - uses: bahmutov/npm-install@v1.4.5 <-- trigger an `npm install`
      - run: npm run nx test store <-- test the "store" project
  test-api:
    runs-on: ubuntu-latest
    name: Test API
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5`
      - run: npm run nx test api
